apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: myweb
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
  name: myweb-ingress
spec:
  rules:
    - host: "{{ .Values.ingressip }}.xip.io"
      http:
        paths:
          - path: /
            backend:
              serviceName: myweb
              servicePort: 80