apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - mykubeapp.azure.tomaskubica.cz
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - mykubeapp.azure.tomaskubica.cz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer