apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myclusterscaling-deployment
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: myhpa
    spec:
      containers:
      - name: myclusterscaling
        image: tkubica/stress
        resources:
          limits:
            cpu: 500m