apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: standardpriority
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: standardpriority
    spec:
      containers:
      - name: myweb
        image: nginx:alpine
        resources:
          requests:
            cpu: "1000m"