apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhpa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myhpa
  template:
    metadata:
      labels:
        app: myhpa
    spec:
      containers:
      - name: myhpa
        image: tkubica/stress
        env:
        - name: STRESS_TIMEOUT
          value: "600"
        resources:
          limits:
            cpu: 200m