kind: Pod
apiVersion: v1
metadata:
  name: anti1
  labels:
    app: anti1
spec:
  containers:
    - name: nginx
      image: nginx:alpine
---
kind: Pod
apiVersion: v1
metadata:
  name: anti2
  labels:
    app: anti2
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - anti1
        topologyKey: color
  containers:
    - name: nginx
      image: nginx:alpine