apiVersion: v1
kind: Pod
metadata:
  name: super-mario
  namespace: default
spec:
  containers:
  - name: myiis
    image: microsoft/iis:nanoserver
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  nodeName: aci-connector