<<<<<<< HEAD
kind: Pod
apiVersion: v1
metadata:
  name: first
  labels:
    app: first
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      resources:
        requests:
          cpu: 100m
          memory: 64M
        limits:
          cpu: 500m
=======
kind: Pod
apiVersion: v1
metadata:
  name: first
  labels:
    app: first
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      resources:
        requests:
          cpu: 100m
          memory: 64M
        limits:
          cpu: 500m
>>>>>>> b0561eb679c2f138f6fe75160a4c763324e96abf
          memory: 256M