kind: Pod
apiVersion: v1
metadata:
  name: cm2-pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["tail"]
      args: ["-f", "/dev/null"]
      env:
        - name: newnamekey1
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: mycfgkey
        - name: newnamekey2
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: mycfgkey2