kind: Pod
apiVersion: v1
metadata:
  name: supervisord
spec:
  containers:
    - name: ubuntu
      image: tkubica/multiprocess
      resources:
        requests:
          cpu: 100m
          memory: 64M
        limits:
          cpu: 500m
          memory: 256M