<<<<<<< HEAD
apiVersion: v1
kind: Pod
metadata:
  name: sidecar
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    ports:
      - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 64M
      limits:
        cpu: 500m
        memory: 256M
  - name: downloader
    image: tutum/curl
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["curl"]
    args: ["https://en.wikipedia.org/wiki/Single-page_application", "-o", "/pod-data/index.html"]
    resources:
      requests:
        cpu: 100m
        memory: 64M
      limits:
        cpu: 500m
=======
apiVersion: v1
kind: Pod
metadata:
  name: sidecar
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    ports:
      - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 64M
      limits:
        cpu: 500m
        memory: 256M
  - name: downloader
    image: tutum/curl
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["curl"]
    args: ["https://en.wikipedia.org/wiki/Single-page_application", "-o", "/pod-data/index.html"]
    resources:
      requests:
        cpu: 100m
        memory: 64M
      limits:
        cpu: 500m
>>>>>>> b0561eb679c2f138f6fe75160a4c763324e96abf
        memory: 256M