apiVersion: v1
kind: Pod
metadata:
  name: sidecar2
spec:
  containers:
  - name: app
    image: tutum/curl
    command: ["tail"]
    args: ["-f", "/dev/null"]
    resources:
      requests:
        cpu: 100m
        memory: 64M
      limits:
        cpu: 500m
        memory: 256M
  - name: ambassador
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 64M
      limits:
        cpu: 500m
        memory: 256M