kind: Pod
apiVersion: v1
metadata:
  name: mypod2
spec:
  containers:
    - name: mypod
      image: nginx:alpine
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        preference:
          matchExpressions:
          - key: color
            operator: In
            values:
            - orange
      - weight: 1
        preference:
          matchExpressions:
          - key: color
            operator: In
            values:
            - red