kind: Pod
apiVersion: v1
metadata:
  name: critical-priority
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "1000m"
  priorityClassName: critical