kind: Pod
apiVersion: v1
metadata:
  name: sec
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["tail"]
      args: ["-f", "/dev/null"]
      env:
        - name: SECRET1
          valueFrom:
            secretKeyRef:
              name: secret1
              key: password
        - name: SECRET2
          valueFrom:
            secretKeyRef:
              name: secret2
              key: password.txt