kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tomas-cluster
  namespace: rbac
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: "user1@tomaskubica.cz"
roleRef:
  kind: Role
  name: myrole
  apiGroup: rbac.authorization.k8s.io