kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: rbac
  name: myrole
rules:
- apiGroups: [""] 
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "watch", "list", "create"]